export const AuditActions = {
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_SUSPENDED: 'USER_SUSPENDED',
  ROLE_CHANGED: 'ROLE_CHANGED',

  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',

  CASH_DROP_CREATED: 'CASH_DROP_CREATED',
  CASH_DROP_REPRINTED: 'CASH_DROP_REPRINTED',
  CASH_DROP_VERIFIED: 'CASH_DROP_VERIFIED',
  CASH_DROP_VARIANCE: 'CASH_DROP_VARIANCE',

  CASH_BANKED: 'CASH_BANKED',

  DEVICE_ASSIGNED: 'DEVICE_ASSIGNED',
  DEVICE_UNASSIGNED: 'DEVICE_UNASSIGNED',

  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
} as const;