export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',

  ACTIVATE = 'ACTIVATE',
  DEACTIVATE = 'DEACTIVATE',
  REACTIVATE = 'REACTIVATE',

  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',

  APPROVE = 'APPROVE',
  REJECT = 'REJECT',

  VERIFY = 'VERIFY',
  RESET_PASSWORD = 'RESET_PASSWORD',
}