export enum Permission {
  // Users
  USER_CREATE = 'USER_CREATE',
  USER_VIEW = 'USER_VIEW',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',

  // Roles
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_VIEW = 'ROLE_VIEW',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',

  // Shift Management
  SHIFT_OPEN = 'SHIFT_OPEN',
  SHIFT_CLOSE = 'SHIFT_CLOSE',
  SHIFT_APPROVE = 'SHIFT_APPROVE',

  // Cash Drops
  CASH_DROP_CREATE = 'CASH_DROP_CREATE',
  CASH_DROP_VERIFY = 'CASH_DROP_VERIFY',

  // Reports
  REPORT_VIEW = 'REPORT_VIEW',
  REPORT_EXPORT = 'REPORT_EXPORT',
}